timer:
  dishwasher_delayed_job_completion_timer:
    name: Dishwasher - Delayed Job Completion Timer
    duration: "00:15:00" # <- Note that the time here. Leave as it is (15 min)
    restore: true
    icon: mdi:dishwasher

  # ...

input_boolean:
  dishwasher_job_cycle:
    name: Dishwasher - Job Cycle
    icon: mdi:dishwasher

  dishwasher_automation_self_trigger:
    name: Dishwasher - Automation Self-trigger
    icon: mdi:dishwasher

  # ...

input_select:
  dishwasher_state_machine:
    name: Dishwasher - State Machine
    options:
      - unplugged
      - idle
      - paused
      - paused_manually
      - paused_overload
      - job_ongoing
      - job_completed
    icon: mdi:dishwasher

  # ...
